-- =====================================================
-- MS.Reservas + Facturacion - redcar_reservas_db
-- PostgreSQL 15+ / 16+
-- =====================================================
-- Dominio: reservas, conductores y extras asociados a la reserva,
-- contratos, check-in / check-out, pagos y facturas.
--
-- Cross-service (FKs ELIMINADAS, referencias blandas id + guid):
--   - id_cliente               -> MS.Clientes
--   - id_vehiculo              -> MS.Catalogo
--   - id_localizacion_recogida -> MS.Localizaciones
--   - id_localizacion_devolucion -> MS.Localizaciones
--   - id_conductor             -> MS.Clientes
--   - id_extra                 -> MS.Catalogo
--
-- FKs internas a este dominio (CONSERVADAS):
--   - contratos.id_reserva, checkin_out.id_contrato,
--     reserva_conductores.id_reserva, reserva_extras.id_reserva,
--     pagos.id_reserva/id_contrato, facturas.id_reserva/id_contrato
-- =====================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS reservas;

-- =====================================================
-- reservas
-- =====================================================
CREATE TABLE reservas.reservas (
    id_reserva INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reserva_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_reserva VARCHAR(20) NOT NULL,
    -- cross-service: clientes
    id_cliente INT NOT NULL,
    cliente_guid UUID NULL,
    -- cross-service: catalogo
    id_vehiculo INT NOT NULL,
    vehiculo_guid UUID NULL,
    -- cross-service: localizaciones
    id_localizacion_recogida INT NOT NULL,
    localizacion_recogida_guid UUID NULL,
    id_localizacion_devolucion INT NOT NULL,
    localizacion_devolucion_guid UUID NULL,
    canal_reserva VARCHAR(20) NOT NULL,
    fecha_hora_recogida TIMESTAMPTZ(0) NOT NULL,
    fecha_hora_devolucion TIMESTAMPTZ(0) NOT NULL,
    subtotal DECIMAL(12,2) NOT NULL,
    valor_impuestos DECIMAL(12,2) NOT NULL,
    valor_extras DECIMAL(12,2) NOT NULL DEFAULT 0,
    valor_deposito_garantia DECIMAL(12,2) NOT NULL DEFAULT 0,
    cargo_one_way DECIMAL(12,2) NOT NULL DEFAULT 0,
    total DECIMAL(12,2) NOT NULL,
    codigo_confirmacion VARCHAR(30) NOT NULL,
    estado_reserva VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    requiere_hold BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_cancelacion_utc TIMESTAMPTZ(0) NULL,
    motivo_cancelacion VARCHAR(250) NULL,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_reservas PRIMARY KEY (id_reserva),
    CONSTRAINT UQ_reservas_GUID UNIQUE (reserva_guid),
    CONSTRAINT UQ_reservas_CODIGO UNIQUE (codigo_reserva),
    CONSTRAINT UQ_reservas_CONFIRMACION UNIQUE (codigo_confirmacion),
    CONSTRAINT CHK_reservas_FECHAS CHECK (fecha_hora_devolucion > fecha_hora_recogida),
    CONSTRAINT CHK_reservas_VALORES CHECK (
        subtotal >= 0 AND valor_impuestos >= 0 AND valor_extras >= 0 AND
        valor_deposito_garantia >= 0 AND cargo_one_way >= 0 AND total >= 0
    ),
    CONSTRAINT CHK_reservas_CANAL CHECK (canal_reserva IN ('WEB','POS','BOOKING','APP','BACKOFFICE')),
    CONSTRAINT CHK_reservas_ESTADO CHECK (estado_reserva IN ('PENDIENTE','CONFIRMADA','CANCELADA','EN_CURSO','FINALIZADA','NO_SHOW'))
);

-- =====================================================
-- reserva_conductores (cross-service: conductor -> clientes)
-- =====================================================
CREATE TABLE reservas.reserva_conductores (
    id_reserva_conductor INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reserva_conductor_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    id_reserva INT NOT NULL,
    -- cross-service: clientes.conductores
    id_conductor INT NOT NULL,
    conductor_guid UUID NULL,
    tipo_conductor VARCHAR(20) NOT NULL DEFAULT 'ADICIONAL',
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    cargo_conductor_joven DECIMAL(10,2) NOT NULL DEFAULT 0,
    estado_reserva_conductor CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_asignacion_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_reserva_conductores PRIMARY KEY (id_reserva_conductor),
    CONSTRAINT UQ_reserva_conductores_GUID UNIQUE (reserva_conductor_guid),
    CONSTRAINT UQ_reserva_conductores UNIQUE (id_reserva, id_conductor),
    CONSTRAINT FK_reserva_conductores_reservas FOREIGN KEY (id_reserva)
        REFERENCES reservas.reservas(id_reserva),
    CONSTRAINT CHK_reserva_conductores_TIPO CHECK (tipo_conductor IN ('TITULAR','ADICIONAL')),
    CONSTRAINT CHK_reserva_conductores_ESTADO CHECK (estado_reserva_conductor IN ('ACT','INA')),
    CONSTRAINT CHK_reserva_conductores_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE)),
    CONSTRAINT CHK_reserva_conductores_CARGO CHECK (cargo_conductor_joven >= 0)
);

-- =====================================================
-- reserva_extras (cross-service: extra -> catalogo)
-- =====================================================
CREATE TABLE reservas.reserva_extras (
    id_reserva_extra INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reserva_extra_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    id_reserva INT NOT NULL,
    -- cross-service: catalogo.extras
    id_extra INT NOT NULL,
    extra_guid UUID NULL,
    cantidad INT NOT NULL,
    valor_unitario_extra DECIMAL(10,2) NOT NULL,
    subtotal_extra DECIMAL(10,2) NOT NULL,
    estado_reserva_extra CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_reserva_extras PRIMARY KEY (id_reserva_extra),
    CONSTRAINT UQ_reserva_extras_GUID UNIQUE (reserva_extra_guid),
    CONSTRAINT UQ_reserva_extras UNIQUE (id_reserva, id_extra),
    CONSTRAINT FK_reserva_extras_reservas FOREIGN KEY (id_reserva)
        REFERENCES reservas.reservas(id_reserva),
    CONSTRAINT CHK_reserva_extras_CANTIDAD CHECK (cantidad > 0),
    CONSTRAINT CHK_reserva_extras_VALORES CHECK (valor_unitario_extra >= 0 AND subtotal_extra >= 0),
    CONSTRAINT CHK_reserva_extras_ESTADO CHECK (estado_reserva_extra IN ('ACT','INA')),
    CONSTRAINT CHK_reserva_extras_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

-- =====================================================
-- contratos (cross-service: cliente, vehiculo)
-- =====================================================
CREATE TABLE reservas.contratos (
    id_contrato INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contrato_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    numero_contrato VARCHAR(30) NOT NULL,
    id_reserva INT NOT NULL,
    -- cross-service: clientes
    id_cliente INT NOT NULL,
    cliente_guid UUID NULL,
    -- cross-service: catalogo
    id_vehiculo INT NOT NULL,
    vehiculo_guid UUID NULL,
    fecha_hora_salida TIMESTAMPTZ(0) NOT NULL,
    fecha_hora_prevista_devolucion TIMESTAMPTZ(0) NOT NULL,
    kilometraje_salida INT NOT NULL,
    nivel_combustible_salida DECIMAL(5,2) NOT NULL,
    estado_contrato VARCHAR(20) NOT NULL DEFAULT 'ABIERTO',
    pdf_url VARCHAR(300) NULL,
    observaciones_contrato VARCHAR(300) NULL,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_contratos PRIMARY KEY (id_contrato),
    CONSTRAINT UQ_contratos_GUID UNIQUE (contrato_guid),
    CONSTRAINT UQ_contratos_NUMERO UNIQUE (numero_contrato),
    CONSTRAINT UQ_contratos_RESERVA UNIQUE (id_reserva),
    CONSTRAINT FK_contratos_reservas FOREIGN KEY (id_reserva)
        REFERENCES reservas.reservas(id_reserva),
    CONSTRAINT CHK_contratos_ESTADO CHECK (estado_contrato IN ('ABIERTO','CERRADO','ANULADO')),
    CONSTRAINT CHK_contratos_FECHAS CHECK (fecha_hora_prevista_devolucion > fecha_hora_salida),
    CONSTRAINT CHK_contratos_COMBUSTIBLE_SALIDA CHECK (nivel_combustible_salida BETWEEN 0 AND 100),
    CONSTRAINT CHK_contratos_KM_SALIDA CHECK (kilometraje_salida >= 0)
);

-- =====================================================
-- checkin_out (interno, FK a contratos se conserva)
-- =====================================================
CREATE TABLE reservas.checkin_out (
    id_check INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    check_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    id_contrato INT NOT NULL,
    tipo_check VARCHAR(10) NOT NULL,
    fecha_hora_check TIMESTAMPTZ(0) NOT NULL,
    kilometraje INT NOT NULL,
    nivel_combustible DECIMAL(5,2) NOT NULL,
    limpio BOOLEAN NOT NULL DEFAULT TRUE,
    observaciones VARCHAR(300) NULL,
    cargo_combustible DECIMAL(10,2) NOT NULL DEFAULT 0,
    cargo_limpieza DECIMAL(10,2) NOT NULL DEFAULT 0,
    cargo_km_extra DECIMAL(10,2) NOT NULL DEFAULT 0,
    creado_por_usuario VARCHAR(100) NOT NULL,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_checkin_out PRIMARY KEY (id_check),
    CONSTRAINT UQ_checkin_out_GUID UNIQUE (check_guid),
    CONSTRAINT FK_checkin_out_contratos FOREIGN KEY (id_contrato)
        REFERENCES reservas.contratos(id_contrato),
    CONSTRAINT CHK_checkin_out_TIPO CHECK (tipo_check IN ('CHECKOUT','CHECKIN')),
    CONSTRAINT CHK_checkin_out_COMBUSTIBLE CHECK (nivel_combustible BETWEEN 0 AND 100),
    CONSTRAINT CHK_checkin_out_KM CHECK (kilometraje >= 0),
    CONSTRAINT CHK_checkin_out_CARGOS CHECK (cargo_combustible >= 0 AND cargo_limpieza >= 0 AND cargo_km_extra >= 0)
);

-- =====================================================
-- pagos (cross-service: cliente)
-- =====================================================
CREATE TABLE reservas.pagos (
    id_pago INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pago_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_pago VARCHAR(30) NOT NULL,
    id_reserva INT NULL,
    id_contrato INT NULL,
    -- cross-service: clientes
    id_cliente INT NOT NULL,
    cliente_guid UUID NULL,
    tipo_pago VARCHAR(20) NOT NULL,
    metodo_pago VARCHAR(20) NOT NULL,
    estado_pago VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    referencia_externa VARCHAR(100) NULL,
    monto DECIMAL(12,2) NOT NULL,
    moneda CHAR(3) NOT NULL DEFAULT 'USD',
    fecha_pago_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    observaciones_pago VARCHAR(300) NULL,
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_pagos PRIMARY KEY (id_pago),
    CONSTRAINT UQ_pagos_GUID UNIQUE (pago_guid),
    CONSTRAINT UQ_pagos_CODIGO UNIQUE (codigo_pago),
    CONSTRAINT FK_pagos_reservas FOREIGN KEY (id_reserva)
        REFERENCES reservas.reservas(id_reserva),
    CONSTRAINT FK_pagos_contratos FOREIGN KEY (id_contrato)
        REFERENCES reservas.contratos(id_contrato),
    CONSTRAINT CHK_pagos_TIPO CHECK (tipo_pago IN ('COBRO','HOLD','REEMBOLSO','AJUSTE')),
    CONSTRAINT CHK_pagos_METODO CHECK (metodo_pago IN ('EFECTIVO','TARJETA','TRANSFERENCIA','PASARELA')),
    CONSTRAINT CHK_pagos_ESTADO CHECK (estado_pago IN ('PENDIENTE','APROBADO','RECHAZADO','ANULADO','REEMBOLSADO')),
    CONSTRAINT CHK_pagos_MONTO CHECK (monto >= 0)
);

-- =====================================================
-- facturas (cross-service: cliente)
-- =====================================================
CREATE TABLE reservas.facturas (
    id_factura INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    factura_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    numero_factura VARCHAR(40) NOT NULL,
    -- cross-service: clientes
    id_cliente INT NOT NULL,
    cliente_guid UUID NULL,
    id_reserva INT NULL,
    id_contrato INT NULL,
    fecha_emision TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    subtotal DECIMAL(12,2) NOT NULL,
    valor_iva DECIMAL(12,2) NOT NULL,
    total DECIMAL(12,2) NOT NULL,
    observaciones_factura VARCHAR(300) NULL,
    origen_canal_factura VARCHAR(50) NULL,
    estado_factura VARCHAR(20) NOT NULL DEFAULT 'EMITIDA',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificacion_ip VARCHAR(45) NULL,
    servicio_origen VARCHAR(50) NOT NULL,
    motivo_inhabilitacion VARCHAR(250) NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_facturas PRIMARY KEY (id_factura),
    CONSTRAINT UQ_facturas_GUID UNIQUE (factura_guid),
    CONSTRAINT UQ_facturas_NUMERO UNIQUE (numero_factura),
    CONSTRAINT FK_facturas_reservas FOREIGN KEY (id_reserva)
        REFERENCES reservas.reservas(id_reserva),
    CONSTRAINT FK_facturas_contratos FOREIGN KEY (id_contrato)
        REFERENCES reservas.contratos(id_contrato),
    CONSTRAINT CHK_facturas_VALORES CHECK (subtotal >= 0 AND valor_iva >= 0 AND total >= 0),
    CONSTRAINT CHK_facturas_ESTADO CHECK (estado_factura IN ('EMITIDA','ANULADA','PAGADA','PENDIENTE')),
    CONSTRAINT CHK_facturas_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

-- =====================================================
-- Indices utiles
-- =====================================================
CREATE INDEX IX_reservas_VEHICULO_FECHAS ON reservas.reservas (id_vehiculo, fecha_hora_recogida, fecha_hora_devolucion, estado_reserva);
CREATE INDEX IX_reservas_CLIENTE ON reservas.reservas (id_cliente, fecha_hora_recogida DESC);
CREATE INDEX IX_reservas_CLIENTE_GUID ON reservas.reservas (cliente_guid);
CREATE INDEX IX_reservas_VEHICULO_GUID ON reservas.reservas (vehiculo_guid);
CREATE INDEX IX_pagos_RESERVA ON reservas.pagos (id_reserva, estado_pago, fecha_pago_utc DESC);
CREATE INDEX IX_pagos_CLIENTE_GUID ON reservas.pagos (cliente_guid);
CREATE INDEX IX_facturas_CLIENTE_GUID ON reservas.facturas (cliente_guid);
CREATE INDEX IX_reserva_conductores_CONDUCTOR_GUID ON reservas.reserva_conductores (conductor_guid);
CREATE INDEX IX_reserva_extras_EXTRA_GUID ON reservas.reserva_extras (extra_guid);
