-- =====================================================
-- MS.Clientes - redcar_clientes_db
-- PostgreSQL 15+ / 16+
-- =====================================================
-- Dominio: clientes finales y conductores asociados.
-- Sin referencias cross-service salientes.
-- =====================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS clientes;

-- =====================================================
-- clientes
-- =====================================================
CREATE TABLE clientes.clientes (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cliente_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_cliente VARCHAR(20) NOT NULL,
    tipo_identificacion VARCHAR(10) NOT NULL,
    numero_identificacion VARCHAR(20) NOT NULL,
    cli_nombre1 VARCHAR(80) NOT NULL,
    cli_nombre2 VARCHAR(80) NULL,
    cli_apellido1 VARCHAR(80) NOT NULL,
    cli_apellido2 VARCHAR(80) NULL,
    fecha_nacimiento DATE NOT NULL,
    cli_telefono VARCHAR(20) NOT NULL,
    cli_correo VARCHAR(120) NOT NULL,
    direccion_principal VARCHAR(200) NULL,
    estado_cliente CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_clientes PRIMARY KEY (id_cliente),
    CONSTRAINT UQ_clientes_GUID UNIQUE (cliente_guid),
    CONSTRAINT UQ_clientes_CODIGO UNIQUE (codigo_cliente),
    CONSTRAINT UQ_clientes_IDENTIFICACION UNIQUE (numero_identificacion),
    CONSTRAINT UQ_clientes_CORREO UNIQUE (cli_correo),
    CONSTRAINT CHK_clientes_ESTADO CHECK (estado_cliente IN ('ACT','INA')),
    CONSTRAINT CHK_clientes_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE)),
    CONSTRAINT CHK_clientes_EDAD CHECK (fecha_nacimiento <= (CURRENT_DATE - INTERVAL '18 years')),
    CONSTRAINT CHK_clientes_TIPO_IDENTIFICACION CHECK (tipo_identificacion IN ('DNI','PAS','RUC','CED'))
);

-- =====================================================
-- conductores (FK a clientes se conserva, mismo dominio)
-- =====================================================
CREATE TABLE clientes.conductores (
    id_conductor INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conductor_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_conductor VARCHAR(20) NOT NULL,
    id_cliente INT NULL,
    tipo_identificacion VARCHAR(10) NOT NULL,
    numero_identificacion VARCHAR(20) NOT NULL,
    con_nombre1 VARCHAR(80) NOT NULL,
    con_nombre2 VARCHAR(80) NULL,
    con_apellido1 VARCHAR(80) NOT NULL,
    con_apellido2 VARCHAR(80) NULL,
    numero_licencia VARCHAR(30) NOT NULL,
    fecha_vencimiento_licencia DATE NOT NULL,
    edad_conductor SMALLINT NOT NULL,
    con_telefono VARCHAR(20) NOT NULL,
    con_correo VARCHAR(120) NOT NULL,
    es_conductor_joven BOOLEAN GENERATED ALWAYS AS (edad_conductor BETWEEN 21 AND 24) STORED,
    estado_conductor CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_conductores PRIMARY KEY (id_conductor),
    CONSTRAINT UQ_conductores_GUID UNIQUE (conductor_guid),
    CONSTRAINT UQ_conductores_CODIGO UNIQUE (codigo_conductor),
    CONSTRAINT UQ_conductores_IDENTIFICACION UNIQUE (numero_identificacion),
    CONSTRAINT UQ_conductores_LICENCIA UNIQUE (numero_licencia),
    CONSTRAINT FK_conductores_clientes FOREIGN KEY (id_cliente)
        REFERENCES clientes.clientes(id_cliente),
    CONSTRAINT CHK_conductores_ESTADO CHECK (estado_conductor IN ('ACT','INA')),
    CONSTRAINT CHK_conductores_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE)),
    CONSTRAINT CHK_conductores_EDAD CHECK (edad_conductor >= 21),
    CONSTRAINT CHK_conductores_TIPO_IDENTIFICACION CHECK (tipo_identificacion IN ('DNI','PAS','CED'))
);

-- =====================================================
-- Indices utiles
-- =====================================================
CREATE INDEX IX_clientes_CORREO ON clientes.clientes (cli_correo);
CREATE INDEX IX_conductores_CLIENTE ON clientes.conductores (id_cliente);
