-- PostgreSQL 15+ / 16+
-- Conversión base desde el DDL SQL Server propuesto
-- Requiere la extensión pgcrypto para gen_random_uuid()

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS rental;
CREATE SCHEMA IF NOT EXISTS security;
CREATE SCHEMA IF NOT EXISTS audit;

/*
  DDL propuesto para el proyecto RedCar / Europcar
  Motor: SQL Server
  Objetivo: extender script.sql con seguridad, contratos, pagos, inventario y auditoría.
  Nota de seguridad: la contraseña visible '12345' NO se almacena en texto plano.
  En ambientes de desarrollo se debe sembrar el hash correspondiente en security.USUARIOS_APP.
*/

-- =====================================================
-- ESQUEMAS
-- =====================================================
-- =====================================================
-- CATÁLOGOS MAESTROS
-- =====================================================
CREATE TABLE rental.PAISES (
    id_pais INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pais_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_iso2 CHAR(2) NOT NULL,
    nombre_pais VARCHAR(100) NOT NULL,
    estado_pais CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PAISES PRIMARY KEY (id_pais),
    CONSTRAINT UQ_PAISES_GUID UNIQUE (pais_guid),
    CONSTRAINT UQ_PAISES_ISO2 UNIQUE (codigo_iso2),
    CONSTRAINT UQ_PAISES_NOMBRE UNIQUE (nombre_pais),
    CONSTRAINT CHK_PAISES_ESTADO CHECK (estado_pais IN ('ACT','INA')),
    CONSTRAINT CHK_PAISES_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

CREATE TABLE rental.CIUDADES (
    id_ciudad INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ciudad_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    id_pais INT NOT NULL,
    nombre_ciudad VARCHAR(100) NOT NULL,
    estado_ciudad CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_CIUDADES PRIMARY KEY (id_ciudad),
    CONSTRAINT UQ_CIUDADES_GUID UNIQUE (ciudad_guid),
    CONSTRAINT UQ_CIUDADES_PAIS_NOMBRE UNIQUE (id_pais, nombre_ciudad),
    CONSTRAINT FK_CIUDADES_PAISES FOREIGN KEY (id_pais) REFERENCES rental.PAISES(id_pais),
    CONSTRAINT CHK_CIUDADES_ESTADO CHECK (estado_ciudad IN ('ACT','INA')),
    CONSTRAINT CHK_CIUDADES_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

CREATE TABLE rental.LOCALIZACIONES (
    id_localizacion INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    localizacion_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_localizacion VARCHAR(20) NOT NULL,
    nombre_localizacion VARCHAR(100) NOT NULL,
    id_ciudad INT NOT NULL,
    direccion_localizacion VARCHAR(200) NOT NULL,
    telefono_contacto VARCHAR(20) NOT NULL,
    correo_contacto VARCHAR(120) NOT NULL,
    horario_atencion VARCHAR(120) NOT NULL,
    zona_horaria VARCHAR(50) NOT NULL DEFAULT 'America/Guayaquil',
    latitud DECIMAL(9,6) NULL,
    longitud DECIMAL(9,6) NULL,
    estado_localizacion CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_LOCALIZACIONES PRIMARY KEY (id_localizacion),
    CONSTRAINT UQ_LOCALIZACIONES_GUID UNIQUE (localizacion_guid),
    CONSTRAINT UQ_LOCALIZACIONES_CODIGO UNIQUE (codigo_localizacion),
    CONSTRAINT FK_LOCALIZACIONES_CIUDADES FOREIGN KEY (id_ciudad) REFERENCES rental.CIUDADES(id_ciudad),
    CONSTRAINT CHK_LOCALIZACIONES_ESTADO CHECK (estado_localizacion IN ('ACT','INA')),
    CONSTRAINT CHK_LOCALIZACIONES_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

CREATE TABLE rental.MARCA_VEHICULOS (
    id_marca INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    marca_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_marca VARCHAR(20) NOT NULL,
    nombre_marca VARCHAR(100) NOT NULL,
    descripcion_marca VARCHAR(250) NULL,
    estado_marca CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_MARCA_VEHICULOS PRIMARY KEY (id_marca),
    CONSTRAINT UQ_MARCA_VEHICULOS_GUID UNIQUE (marca_guid),
    CONSTRAINT UQ_MARCA_VEHICULOS_CODIGO UNIQUE (codigo_marca),
    CONSTRAINT UQ_MARCA_VEHICULOS_NOMBRE UNIQUE (nombre_marca),
    CONSTRAINT CHK_MARCA_VEHICULOS_ESTADO CHECK (estado_marca IN ('ACT','INA')),
    CONSTRAINT CHK_MARCA_VEHICULOS_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

CREATE TABLE rental.CATEGORIA_VEHICULOS (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    categoria_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_categoria VARCHAR(20) NOT NULL,
    nombre_categoria VARCHAR(100) NOT NULL,
    descripcion_categoria VARCHAR(250) NULL,
    kilometraje_ilimitado BOOLEAN NOT NULL DEFAULT TRUE,
    limite_km_dia INT NULL,
    cargo_km_excedente DECIMAL(10,2) NULL,
    estado_categoria CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_CATEGORIA_VEHICULOS PRIMARY KEY (id_categoria),
    CONSTRAINT UQ_CATEGORIA_VEHICULOS_GUID UNIQUE (categoria_guid),
    CONSTRAINT UQ_CATEGORIA_VEHICULOS_CODIGO UNIQUE (codigo_categoria),
    CONSTRAINT UQ_CATEGORIA_VEHICULOS_NOMBRE UNIQUE (nombre_categoria),
    CONSTRAINT CHK_CATEGORIA_ESTADO CHECK (estado_categoria IN ('ACT','INA')),
    CONSTRAINT CHK_CATEGORIA_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE)),
    CONSTRAINT CHK_CATEGORIA_KM CHECK (
        (kilometraje_ilimitado = TRUE AND limite_km_dia IS NULL AND cargo_km_excedente IS NULL)
        OR
        (kilometraje_ilimitado = FALSE AND limite_km_dia > 0 AND cargo_km_excedente >= 0)
    )
);

CREATE TABLE rental.EXTRAS (
    id_extra INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    extra_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_extra VARCHAR(20) NOT NULL,
    nombre_extra VARCHAR(100) NOT NULL,
    descripcion_extra VARCHAR(250) NOT NULL,
    tipo_extra VARCHAR(20) NOT NULL DEFAULT 'SERVICIO',
    requiere_stock BOOLEAN NOT NULL DEFAULT FALSE,
    valor_fijo DECIMAL(10,2) NOT NULL,
    estado_extra CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_EXTRAS PRIMARY KEY (id_extra),
    CONSTRAINT UQ_EXTRAS_GUID UNIQUE (extra_guid),
    CONSTRAINT UQ_EXTRAS_CODIGO UNIQUE (codigo_extra),
    CONSTRAINT CHK_EXTRAS_ESTADO CHECK (estado_extra IN ('ACT','INA')),
    CONSTRAINT CHK_EXTRAS_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE)),
    CONSTRAINT CHK_EXTRAS_VALOR_FIJO CHECK (valor_fijo >= 0),
    CONSTRAINT CHK_EXTRAS_TIPO CHECK (tipo_extra IN ('SERVICIO','FISICO','SEGURO'))
);

CREATE TABLE rental.LOCALIZACION_EXTRA_STOCK (
    id_localizacion_extra_stock INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stock_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    id_localizacion INT NOT NULL,
    id_extra INT NOT NULL,
    stock_disponible INT NOT NULL,
    stock_reservado INT NOT NULL DEFAULT 0,
    estado_stock CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_LOCALIZACION_EXTRA_STOCK PRIMARY KEY (id_localizacion_extra_stock),
    CONSTRAINT UQ_LOCALIZACION_EXTRA_STOCK_GUID UNIQUE (stock_guid),
    CONSTRAINT UQ_LOCALIZACION_EXTRA_STOCK UNIQUE (id_localizacion, id_extra),
    CONSTRAINT FK_LOCALIZACION_EXTRA_STOCK_LOCALIZACIONES FOREIGN KEY (id_localizacion) REFERENCES rental.LOCALIZACIONES(id_localizacion),
    CONSTRAINT FK_LOCALIZACION_EXTRA_STOCK_EXTRAS FOREIGN KEY (id_extra) REFERENCES rental.EXTRAS(id_extra),
    CONSTRAINT CHK_LOCALIZACION_EXTRA_STOCK_VALORES CHECK (stock_disponible >= 0 AND stock_reservado >= 0 AND stock_reservado <= stock_disponible),
    CONSTRAINT CHK_LOCALIZACION_EXTRA_STOCK_ESTADO CHECK (estado_stock IN ('ACT','INA')),
    CONSTRAINT CHK_LOCALIZACION_EXTRA_STOCK_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

-- =====================================================
-- NÚCLEO OPERATIVO
-- =====================================================
CREATE TABLE rental.CLIENTES (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cliente_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_cliente VARCHAR(20) NOT NULL,
    tipo_identificacion VARCHAR(10) NOT NULL,
    numero_identificacion VARCHAR(20) NOT NULL,
    cli_nombre1 VARCHAR(80) NOT NULL,
    cli_nombre2 VARCHAR(80) NULL,
    cli_apellido1 VARCHAR(80) NOT NULL,
    cli_apellido2 VARCHAR(80) NULL,
    fecha_nacimiento DATE NOT NULL,
    cli_telefono VARCHAR(20) NOT NULL,
    cli_correo VARCHAR(120) NOT NULL,
    direccion_principal VARCHAR(200) NULL,
    estado_cliente CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (id_cliente),
    CONSTRAINT UQ_CLIENTES_GUID UNIQUE (cliente_guid),
    CONSTRAINT UQ_CLIENTES_CODIGO UNIQUE (codigo_cliente),
    CONSTRAINT UQ_CLIENTES_IDENTIFICACION UNIQUE (numero_identificacion),
    CONSTRAINT UQ_CLIENTES_CORREO UNIQUE (cli_correo),
    CONSTRAINT CHK_CLIENTES_ESTADO CHECK (estado_cliente IN ('ACT','INA')),
    CONSTRAINT CHK_CLIENTES_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE)),
    CONSTRAINT CHK_CLIENTES_EDAD CHECK (fecha_nacimiento <= (CURRENT_DATE - INTERVAL '18 years')),
    CONSTRAINT CHK_CLIENTES_TIPO_IDENTIFICACION CHECK (tipo_identificacion IN ('DNI','PAS','RUC','CED'))
);

CREATE TABLE rental.CONDUCTORES (
    id_conductor INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conductor_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_conductor VARCHAR(20) NOT NULL,
    id_cliente INT NULL,
    tipo_identificacion VARCHAR(10) NOT NULL,
    numero_identificacion VARCHAR(20) NOT NULL,
    con_nombre1 VARCHAR(80) NOT NULL,
    con_nombre2 VARCHAR(80) NULL,
    con_apellido1 VARCHAR(80) NOT NULL,
    con_apellido2 VARCHAR(80) NULL,
    numero_licencia VARCHAR(30) NOT NULL,
    fecha_vencimiento_licencia DATE NOT NULL,
    edad_conductor SMALLINT NOT NULL,
    con_telefono VARCHAR(20) NOT NULL,
    con_correo VARCHAR(120) NOT NULL,
    es_conductor_joven BOOLEAN GENERATED ALWAYS AS (edad_conductor BETWEEN 21 AND 24) STORED,
    estado_conductor CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_CONDUCTORES PRIMARY KEY (id_conductor),
    CONSTRAINT UQ_CONDUCTORES_GUID UNIQUE (conductor_guid),
    CONSTRAINT UQ_CONDUCTORES_CODIGO UNIQUE (codigo_conductor),
    CONSTRAINT UQ_CONDUCTORES_IDENTIFICACION UNIQUE (numero_identificacion),
    CONSTRAINT UQ_CONDUCTORES_LICENCIA UNIQUE (numero_licencia),
    CONSTRAINT FK_CONDUCTORES_CLIENTES FOREIGN KEY (id_cliente) REFERENCES rental.CLIENTES(id_cliente),
    CONSTRAINT CHK_CONDUCTORES_ESTADO CHECK (estado_conductor IN ('ACT','INA')),
    CONSTRAINT CHK_CONDUCTORES_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE)),
    CONSTRAINT CHK_CONDUCTORES_EDAD CHECK (edad_conductor >= 21),
    CONSTRAINT CHK_CONDUCTORES_TIPO_IDENTIFICACION CHECK (tipo_identificacion IN ('DNI','PAS','CED'))
);

CREATE TABLE rental.VEHICULOS (
    id_vehiculo INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vehiculo_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_interno_vehiculo VARCHAR(20) NOT NULL,
    placa_vehiculo VARCHAR(15) NOT NULL,
    id_marca INT NOT NULL,
    id_categoria INT NOT NULL,
    modelo_vehiculo VARCHAR(50) NOT NULL,
    anio_fabricacion SMALLINT NOT NULL,
    color_vehiculo VARCHAR(30) NOT NULL,
    tipo_combustible VARCHAR(20) NOT NULL,
    tipo_transmision VARCHAR(20) NOT NULL,
    capacidad_pasajeros SMALLINT NOT NULL,
    capacidad_maletas SMALLINT NOT NULL,
    numero_puertas SMALLINT NOT NULL,
    localizacion_actual INT NOT NULL,
    precio_base_dia DECIMAL(10,2) NOT NULL,
    kilometraje_actual INT NOT NULL,
    aire_acondicionado BOOLEAN NOT NULL DEFAULT TRUE,
    estado_operativo VARCHAR(20) NOT NULL DEFAULT 'DISPONIBLE',
    observaciones_generales VARCHAR(300) NULL,
    imagen_referencial_url VARCHAR(300) NULL,
    estado_vehiculo CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    origen_registro VARCHAR(20) NOT NULL,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_VEHICULOS PRIMARY KEY (id_vehiculo),
    CONSTRAINT UQ_VEHICULOS_GUID UNIQUE (vehiculo_guid),
    CONSTRAINT UQ_VEHICULOS_CODIGO UNIQUE (codigo_interno_vehiculo),
    CONSTRAINT UQ_VEHICULOS_PLACA UNIQUE (placa_vehiculo),
    CONSTRAINT FK_VEHICULOS_LOCALIZACIONES FOREIGN KEY (localizacion_actual) REFERENCES rental.LOCALIZACIONES(id_localizacion),
    CONSTRAINT FK_VEHICULOS_MARCA FOREIGN KEY (id_marca) REFERENCES rental.MARCA_VEHICULOS(id_marca),
    CONSTRAINT FK_VEHICULOS_CATEGORIA FOREIGN KEY (id_categoria) REFERENCES rental.CATEGORIA_VEHICULOS(id_categoria),
    CONSTRAINT CHK_VEHICULOS_ESTADO CHECK (estado_vehiculo IN ('ACT','INA')),
    CONSTRAINT CHK_VEHICULOS_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE)),
    CONSTRAINT CHK_VEHICULOS_PRECIO_BASE CHECK (precio_base_dia > 0),
    CONSTRAINT CHK_VEHICULOS_KILOMETRAJE CHECK (kilometraje_actual >= 0),
    CONSTRAINT CHK_VEHICULOS_CAP_PASAJEROS CHECK (capacidad_pasajeros > 0),
    CONSTRAINT CHK_VEHICULOS_CAP_MALETAS CHECK (capacidad_maletas >= 0),
    CONSTRAINT CHK_VEHICULOS_NUM_PUERTAS CHECK (numero_puertas > 0),
    CONSTRAINT CHK_VEHICULOS_ANIO CHECK (anio_fabricacion BETWEEN 1990 AND (EXTRACT(YEAR FROM CURRENT_DATE)::INT + 1)),
    CONSTRAINT CHK_VEHICULOS_COMBUSTIBLE CHECK (tipo_combustible IN ('GASOLINA','DIESEL','HIBRIDO','ELECTRICO')),
    CONSTRAINT CHK_VEHICULOS_TRANSMISION CHECK (tipo_transmision IN ('AUTOMATICA','MANUAL')),
    CONSTRAINT CHK_VEHICULOS_ESTADO_OPERATIVO CHECK (estado_operativo IN ('DISPONIBLE','RESERVADO','ALQUILADO','MANTENIMIENTO','TALLER','FUERA_SERVICIO'))
);

CREATE TABLE rental.RESERVAS (
    id_reserva INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reserva_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_reserva VARCHAR(20) NOT NULL,
    id_cliente INT NOT NULL,
    id_vehiculo INT NOT NULL,
    id_localizacion_recogida INT NOT NULL,
    id_localizacion_devolucion INT NOT NULL,
    canal_reserva VARCHAR(20) NOT NULL,
    fecha_hora_recogida TIMESTAMPTZ(0) NOT NULL,
    fecha_hora_devolucion TIMESTAMPTZ(0) NOT NULL,
    subtotal DECIMAL(12,2) NOT NULL,
    valor_impuestos DECIMAL(12,2) NOT NULL,
    valor_extras DECIMAL(12,2) NOT NULL DEFAULT 0,
    valor_deposito_garantia DECIMAL(12,2) NOT NULL DEFAULT 0,
    cargo_one_way DECIMAL(12,2) NOT NULL DEFAULT 0,
    total DECIMAL(12,2) NOT NULL,
    codigo_confirmacion VARCHAR(30) NOT NULL,
    estado_reserva VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    requiere_hold BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_cancelacion_utc TIMESTAMPTZ(0) NULL,
    motivo_cancelacion VARCHAR(250) NULL,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_RESERVAS PRIMARY KEY (id_reserva),
    CONSTRAINT UQ_RESERVAS_GUID UNIQUE (reserva_guid),
    CONSTRAINT UQ_RESERVAS_CODIGO UNIQUE (codigo_reserva),
    CONSTRAINT UQ_RESERVAS_CONFIRMACION UNIQUE (codigo_confirmacion),
    CONSTRAINT FK_RESERVAS_CLIENTES FOREIGN KEY (id_cliente) REFERENCES rental.CLIENTES(id_cliente),
    CONSTRAINT FK_RESERVAS_VEHICULOS FOREIGN KEY (id_vehiculo) REFERENCES rental.VEHICULOS(id_vehiculo),
    CONSTRAINT FK_RESERVAS_LOCALIZACION_RECOGIDA FOREIGN KEY (id_localizacion_recogida) REFERENCES rental.LOCALIZACIONES(id_localizacion),
    CONSTRAINT FK_RESERVAS_LOCALIZACION_DEVOLUCION FOREIGN KEY (id_localizacion_devolucion) REFERENCES rental.LOCALIZACIONES(id_localizacion),
    CONSTRAINT CHK_RESERVAS_FECHAS CHECK (fecha_hora_devolucion > fecha_hora_recogida),
    CONSTRAINT CHK_RESERVAS_VALORES CHECK (
        subtotal >= 0 AND valor_impuestos >= 0 AND valor_extras >= 0 AND
        valor_deposito_garantia >= 0 AND cargo_one_way >= 0 AND total >= 0
    ),
    CONSTRAINT CHK_RESERVAS_CANAL CHECK (canal_reserva IN ('WEB','POS','BOOKING','APP','BACKOFFICE')),
    CONSTRAINT CHK_RESERVAS_ESTADO CHECK (estado_reserva IN ('PENDIENTE','CONFIRMADA','CANCELADA','EN_CURSO','FINALIZADA','NO_SHOW'))
);

CREATE TABLE rental.RESERVA_CONDUCTORES (
    id_reserva_conductor INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reserva_conductor_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    id_reserva INT NOT NULL,
    id_conductor INT NOT NULL,
    tipo_conductor VARCHAR(20) NOT NULL DEFAULT 'ADICIONAL',
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    cargo_conductor_joven DECIMAL(10,2) NOT NULL DEFAULT 0,
    estado_reserva_conductor CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_asignacion_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_RESERVA_CONDUCTORES PRIMARY KEY (id_reserva_conductor),
    CONSTRAINT UQ_RESERVA_CONDUCTORES_GUID UNIQUE (reserva_conductor_guid),
    CONSTRAINT UQ_RESERVA_CONDUCTORES UNIQUE (id_reserva, id_conductor),
    CONSTRAINT FK_RESERVA_CONDUCTORES_RESERVAS FOREIGN KEY (id_reserva) REFERENCES rental.RESERVAS(id_reserva),
    CONSTRAINT FK_RESERVA_CONDUCTORES_CONDUCTORES FOREIGN KEY (id_conductor) REFERENCES rental.CONDUCTORES(id_conductor),
    CONSTRAINT CHK_RESERVA_CONDUCTORES_TIPO CHECK (tipo_conductor IN ('TITULAR','ADICIONAL')),
    CONSTRAINT CHK_RESERVA_CONDUCTORES_ESTADO CHECK (estado_reserva_conductor IN ('ACT','INA')),
    CONSTRAINT CHK_RESERVA_CONDUCTORES_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE)),
    CONSTRAINT CHK_RESERVA_CONDUCTORES_CARGO CHECK (cargo_conductor_joven >= 0)
);

CREATE TABLE rental.RESERVA_EXTRAS (
    id_reserva_extra INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reserva_extra_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    id_reserva INT NOT NULL,
    id_extra INT NOT NULL,
    cantidad INT NOT NULL,
    valor_unitario_extra DECIMAL(10,2) NOT NULL,
    subtotal_extra DECIMAL(10,2) NOT NULL,
    estado_reserva_extra CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_RESERVA_EXTRAS PRIMARY KEY (id_reserva_extra),
    CONSTRAINT UQ_RESERVA_EXTRAS_GUID UNIQUE (reserva_extra_guid),
    CONSTRAINT UQ_RESERVA_EXTRAS UNIQUE (id_reserva, id_extra),
    CONSTRAINT FK_RESERVA_EXTRAS_RESERVAS FOREIGN KEY (id_reserva) REFERENCES rental.RESERVAS(id_reserva),
    CONSTRAINT FK_RESERVA_EXTRAS_EXTRAS FOREIGN KEY (id_extra) REFERENCES rental.EXTRAS(id_extra),
    CONSTRAINT CHK_RESERVA_EXTRAS_CANTIDAD CHECK (cantidad > 0),
    CONSTRAINT CHK_RESERVA_EXTRAS_VALORES CHECK (valor_unitario_extra >= 0 AND subtotal_extra >= 0),
    CONSTRAINT CHK_RESERVA_EXTRAS_ESTADO CHECK (estado_reserva_extra IN ('ACT','INA')),
    CONSTRAINT CHK_RESERVA_EXTRAS_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

CREATE TABLE rental.CONTRATOS (
    id_contrato INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contrato_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    numero_contrato VARCHAR(30) NOT NULL,
    id_reserva INT NOT NULL,
    id_cliente INT NOT NULL,
    id_vehiculo INT NOT NULL,
    fecha_hora_salida TIMESTAMPTZ(0) NOT NULL,
    fecha_hora_prevista_devolucion TIMESTAMPTZ(0) NOT NULL,
    kilometraje_salida INT NOT NULL,
    nivel_combustible_salida DECIMAL(5,2) NOT NULL,
    estado_contrato VARCHAR(20) NOT NULL DEFAULT 'ABIERTO',
    pdf_url VARCHAR(300) NULL,
    observaciones_contrato VARCHAR(300) NULL,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_CONTRATOS PRIMARY KEY (id_contrato),
    CONSTRAINT UQ_CONTRATOS_GUID UNIQUE (contrato_guid),
    CONSTRAINT UQ_CONTRATOS_NUMERO UNIQUE (numero_contrato),
    CONSTRAINT UQ_CONTRATOS_RESERVA UNIQUE (id_reserva),
    CONSTRAINT FK_CONTRATOS_RESERVAS FOREIGN KEY (id_reserva) REFERENCES rental.RESERVAS(id_reserva),
    CONSTRAINT FK_CONTRATOS_CLIENTES FOREIGN KEY (id_cliente) REFERENCES rental.CLIENTES(id_cliente),
    CONSTRAINT FK_CONTRATOS_VEHICULOS FOREIGN KEY (id_vehiculo) REFERENCES rental.VEHICULOS(id_vehiculo),
    CONSTRAINT CHK_CONTRATOS_ESTADO CHECK (estado_contrato IN ('ABIERTO','CERRADO','ANULADO')),
    CONSTRAINT CHK_CONTRATOS_FECHAS CHECK (fecha_hora_prevista_devolucion > fecha_hora_salida),
    CONSTRAINT CHK_CONTRATOS_COMBUSTIBLE_SALIDA CHECK (nivel_combustible_salida BETWEEN 0 AND 100),
    CONSTRAINT CHK_CONTRATOS_KM_SALIDA CHECK (kilometraje_salida >= 0)
);

CREATE TABLE rental.CHECKIN_OUT (
    id_check INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    check_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    id_contrato INT NOT NULL,
    tipo_check VARCHAR(10) NOT NULL,
    fecha_hora_check TIMESTAMPTZ(0) NOT NULL,
    kilometraje INT NOT NULL,
    nivel_combustible DECIMAL(5,2) NOT NULL,
    limpio BOOLEAN NOT NULL DEFAULT TRUE,
    observaciones VARCHAR(300) NULL,
    cargo_combustible DECIMAL(10,2) NOT NULL DEFAULT 0,
    cargo_limpieza DECIMAL(10,2) NOT NULL DEFAULT 0,
    cargo_km_extra DECIMAL(10,2) NOT NULL DEFAULT 0,
    creado_por_usuario VARCHAR(100) NOT NULL,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_CHECKIN_OUT PRIMARY KEY (id_check),
    CONSTRAINT UQ_CHECKIN_OUT_GUID UNIQUE (check_guid),
    CONSTRAINT FK_CHECKIN_OUT_CONTRATOS FOREIGN KEY (id_contrato) REFERENCES rental.CONTRATOS(id_contrato),
    CONSTRAINT CHK_CHECKIN_OUT_TIPO CHECK (tipo_check IN ('CHECKOUT','CHECKIN')),
    CONSTRAINT CHK_CHECKIN_OUT_COMBUSTIBLE CHECK (nivel_combustible BETWEEN 0 AND 100),
    CONSTRAINT CHK_CHECKIN_OUT_KM CHECK (kilometraje >= 0),
    CONSTRAINT CHK_CHECKIN_OUT_CARGOS CHECK (cargo_combustible >= 0 AND cargo_limpieza >= 0 AND cargo_km_extra >= 0)
);

CREATE TABLE rental.PAGOS (
    id_pago INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pago_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_pago VARCHAR(30) NOT NULL,
    id_reserva INT NULL,
    id_contrato INT NULL,
    id_cliente INT NOT NULL,
    tipo_pago VARCHAR(20) NOT NULL,
    metodo_pago VARCHAR(20) NOT NULL,
    estado_pago VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    referencia_externa VARCHAR(100) NULL,
    monto DECIMAL(12,2) NOT NULL,
    moneda CHAR(3) NOT NULL DEFAULT 'USD',
    fecha_pago_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    observaciones_pago VARCHAR(300) NULL,
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PAGOS PRIMARY KEY (id_pago),
    CONSTRAINT UQ_PAGOS_GUID UNIQUE (pago_guid),
    CONSTRAINT UQ_PAGOS_CODIGO UNIQUE (codigo_pago),
    CONSTRAINT FK_PAGOS_RESERVAS FOREIGN KEY (id_reserva) REFERENCES rental.RESERVAS(id_reserva),
    CONSTRAINT FK_PAGOS_CONTRATOS FOREIGN KEY (id_contrato) REFERENCES rental.CONTRATOS(id_contrato),
    CONSTRAINT FK_PAGOS_CLIENTES FOREIGN KEY (id_cliente) REFERENCES rental.CLIENTES(id_cliente),
    CONSTRAINT CHK_PAGOS_TIPO CHECK (tipo_pago IN ('COBRO','HOLD','REEMBOLSO','AJUSTE')),
    CONSTRAINT CHK_PAGOS_METODO CHECK (metodo_pago IN ('EFECTIVO','TARJETA','TRANSFERENCIA','PASARELA')),
    CONSTRAINT CHK_PAGOS_ESTADO CHECK (estado_pago IN ('PENDIENTE','APROBADO','RECHAZADO','ANULADO','REEMBOLSADO')),
    CONSTRAINT CHK_PAGOS_MONTO CHECK (monto >= 0)
);

CREATE TABLE rental.FACTURAS (
    id_factura INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    factura_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    numero_factura VARCHAR(40) NOT NULL,
    id_cliente INT NOT NULL,
    id_reserva INT NULL,
    id_contrato INT NULL,
    fecha_emision TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    subtotal DECIMAL(12,2) NOT NULL,
    valor_iva DECIMAL(12,2) NOT NULL,
    total DECIMAL(12,2) NOT NULL,
    observaciones_factura VARCHAR(300) NULL,
    origen_canal_factura VARCHAR(50) NULL,
    estado_factura VARCHAR(20) NOT NULL DEFAULT 'EMITIDA',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificacion_ip VARCHAR(45) NULL,
    servicio_origen VARCHAR(50) NOT NULL,
    motivo_inhabilitacion VARCHAR(250) NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_FACTURAS PRIMARY KEY (id_factura),
    CONSTRAINT UQ_FACTURAS_GUID UNIQUE (factura_guid),
    CONSTRAINT UQ_FACTURAS_NUMERO UNIQUE (numero_factura),
    CONSTRAINT FK_FACTURAS_CLIENTES FOREIGN KEY (id_cliente) REFERENCES rental.CLIENTES(id_cliente),
    CONSTRAINT FK_FACTURAS_RESERVAS FOREIGN KEY (id_reserva) REFERENCES rental.RESERVAS(id_reserva),
    CONSTRAINT FK_FACTURAS_CONTRATOS FOREIGN KEY (id_contrato) REFERENCES rental.CONTRATOS(id_contrato),
    CONSTRAINT CHK_FACTURAS_VALORES CHECK (subtotal >= 0 AND valor_iva >= 0 AND total >= 0),
    CONSTRAINT CHK_FACTURAS_ESTADO CHECK (estado_factura IN ('EMITIDA','ANULADA','PAGADA','PENDIENTE')),
    CONSTRAINT CHK_FACTURAS_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

CREATE TABLE rental.MANTENIMIENTOS (
    id_mantenimiento INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mantenimiento_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_mantenimiento VARCHAR(30) NOT NULL,
    id_vehiculo INT NOT NULL,
    tipo_mantenimiento VARCHAR(20) NOT NULL,
    fecha_inicio_utc TIMESTAMPTZ(0) NOT NULL,
    fecha_fin_utc TIMESTAMPTZ(0) NULL,
    kilometraje_mantenimiento INT NOT NULL,
    costo_mantenimiento DECIMAL(12,2) NOT NULL DEFAULT 0,
    proveedor_taller VARCHAR(120) NULL,
    estado_mantenimiento VARCHAR(20) NOT NULL DEFAULT 'ABIERTO',
    observaciones VARCHAR(300) NULL,
    creado_por_usuario VARCHAR(100) NOT NULL,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_MANTENIMIENTOS PRIMARY KEY (id_mantenimiento),
    CONSTRAINT UQ_MANTENIMIENTOS_GUID UNIQUE (mantenimiento_guid),
    CONSTRAINT UQ_MANTENIMIENTOS_CODIGO UNIQUE (codigo_mantenimiento),
    CONSTRAINT FK_MANTENIMIENTOS_VEHICULOS FOREIGN KEY (id_vehiculo) REFERENCES rental.VEHICULOS(id_vehiculo),
    CONSTRAINT CHK_MANTENIMIENTOS_TIPO CHECK (tipo_mantenimiento IN ('PREVENTIVO','CORRECTIVO','TALLER')),
    CONSTRAINT CHK_MANTENIMIENTOS_ESTADO CHECK (estado_mantenimiento IN ('ABIERTO','CERRADO','ANULADO')),
    CONSTRAINT CHK_MANTENIMIENTOS_KM CHECK (kilometraje_mantenimiento >= 0),
    CONSTRAINT CHK_MANTENIMIENTOS_COSTO CHECK (costo_mantenimiento >= 0),
    CONSTRAINT CHK_MANTENIMIENTOS_FECHAS CHECK (fecha_fin_utc IS NULL OR fecha_fin_utc >= fecha_inicio_utc)
);

-- =====================================================
-- SEGURIDAD DE APLICACIÓN Y API
-- =====================================================
CREATE TABLE security.ROLES (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rol_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    nombre_rol VARCHAR(50) NOT NULL,
    descripcion_rol VARCHAR(200) NULL,
    es_sistema BOOLEAN NOT NULL DEFAULT FALSE,
    estado_rol CHAR(3) NOT NULL DEFAULT 'ACT',
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SECURITY_ROLES PRIMARY KEY (id_rol),
    CONSTRAINT UQ_SECURITY_ROLES_GUID UNIQUE (rol_guid),
    CONSTRAINT UQ_SECURITY_ROLES_NOMBRE UNIQUE (nombre_rol),
    CONSTRAINT CHK_SECURITY_ROLES_ESTADO CHECK (estado_rol IN ('ACT','INA'))
);

CREATE TABLE security.PERMISOS (
    id_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    permiso_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_permiso VARCHAR(80) NOT NULL,
    modulo VARCHAR(50) NOT NULL,
    accion VARCHAR(30) NOT NULL,
    descripcion_permiso VARCHAR(200) NULL,
    estado_permiso CHAR(3) NOT NULL DEFAULT 'ACT',
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SECURITY_PERMISOS PRIMARY KEY (id_permiso),
    CONSTRAINT UQ_SECURITY_PERMISOS_GUID UNIQUE (permiso_guid),
    CONSTRAINT UQ_SECURITY_PERMISOS_CODIGO UNIQUE (codigo_permiso),
    CONSTRAINT CHK_SECURITY_PERMISOS_ESTADO CHECK (estado_permiso IN ('ACT','INA')),
    CONSTRAINT CHK_SECURITY_PERMISOS_ACCION CHECK (accion IN ('CREATE','READ','UPDATE','DELETE','APPROVE','EXPORT','LOGIN'))
);

CREATE TABLE security.USUARIOS_APP (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    username VARCHAR(50) NOT NULL,
    correo VARCHAR(120) NOT NULL,
    password_hash VARCHAR(500) NOT NULL,
    password_salt VARCHAR(250) NOT NULL,
    password_hint VARCHAR(100) NULL,
    requiere_cambio_password BOOLEAN NOT NULL DEFAULT TRUE,
    estado_usuario CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    intentos_fallidos SMALLINT NOT NULL DEFAULT 0,
    bloqueado_hasta_utc TIMESTAMPTZ(0) NULL,
    ultimo_login_utc TIMESTAMPTZ(0) NULL,
    id_cliente INT NULL,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SECURITY_USUARIOS_APP PRIMARY KEY (id_usuario),
    CONSTRAINT UQ_SECURITY_USUARIOS_APP_GUID UNIQUE (usuario_guid),
    CONSTRAINT UQ_SECURITY_USUARIOS_APP_USERNAME UNIQUE (username),
    CONSTRAINT UQ_SECURITY_USUARIOS_APP_CORREO UNIQUE (correo),
    CONSTRAINT FK_SECURITY_USUARIOS_APP_CLIENTES FOREIGN KEY (id_cliente) REFERENCES rental.CLIENTES(id_cliente),
    CONSTRAINT CHK_SECURITY_USUARIOS_APP_ESTADO CHECK (estado_usuario IN ('ACT','INA','BLQ')),
    CONSTRAINT CHK_SECURITY_USUARIOS_APP_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE)),
    CONSTRAINT CHK_SECURITY_USUARIOS_APP_ACTIVO CHECK (activo IN (FALSE, TRUE)),
    CONSTRAINT CHK_SECURITY_USUARIOS_APP_INTENTOS CHECK (intentos_fallidos >= 0)
);

CREATE TABLE security.USUARIOS_ROLES (
    id_usuario_rol INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario INT NOT NULL,
    id_rol INT NOT NULL,
    estado_usuario_rol CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SECURITY_USUARIOS_ROLES PRIMARY KEY (id_usuario_rol),
    CONSTRAINT UQ_SECURITY_USUARIOS_ROLES UNIQUE (id_usuario, id_rol),
    CONSTRAINT FK_SECURITY_USUARIOS_ROLES_USUARIOS FOREIGN KEY (id_usuario) REFERENCES security.USUARIOS_APP(id_usuario),
    CONSTRAINT FK_SECURITY_USUARIOS_ROLES_ROLES FOREIGN KEY (id_rol) REFERENCES security.ROLES(id_rol),
    CONSTRAINT CHK_SECURITY_USUARIOS_ROLES_ESTADO CHECK (estado_usuario_rol IN ('ACT','INA')),
    CONSTRAINT CHK_SECURITY_USUARIOS_ROLES_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

CREATE TABLE security.ROLES_PERMISOS (
    id_rol_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_rol INT NOT NULL,
    id_permiso INT NOT NULL,
    estado_rol_permiso CHAR(3) NOT NULL DEFAULT 'ACT',
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SECURITY_ROLES_PERMISOS PRIMARY KEY (id_rol_permiso),
    CONSTRAINT UQ_SECURITY_ROLES_PERMISOS UNIQUE (id_rol, id_permiso),
    CONSTRAINT FK_SECURITY_ROLES_PERMISOS_ROLES FOREIGN KEY (id_rol) REFERENCES security.ROLES(id_rol),
    CONSTRAINT FK_SECURITY_ROLES_PERMISOS_PERMISOS FOREIGN KEY (id_permiso) REFERENCES security.PERMISOS(id_permiso),
    CONSTRAINT CHK_SECURITY_ROLES_PERMISOS_ESTADO CHECK (estado_rol_permiso IN ('ACT','INA'))
);

CREATE TABLE security.SESIONES (
    id_sesion BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sesion_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    id_usuario INT NOT NULL,
    token_id VARCHAR(120) NOT NULL,
    refresh_token_hash VARCHAR(500) NULL,
    ip_origen VARCHAR(45) NULL,
    user_agent VARCHAR(300) NULL,
    fecha_inicio_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    fecha_expiracion_utc TIMESTAMPTZ(0) NOT NULL,
    fecha_cierre_utc TIMESTAMPTZ(0) NULL,
    estado_sesion VARCHAR(20) NOT NULL DEFAULT 'ACTIVA',
    creado_por_usuario VARCHAR(100) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SECURITY_SESIONES PRIMARY KEY (id_sesion),
    CONSTRAINT UQ_SECURITY_SESIONES_GUID UNIQUE (sesion_guid),
    CONSTRAINT UQ_SECURITY_SESIONES_TOKEN UNIQUE (token_id),
    CONSTRAINT FK_SECURITY_SESIONES_USUARIOS FOREIGN KEY (id_usuario) REFERENCES security.USUARIOS_APP(id_usuario),
    CONSTRAINT CHK_SECURITY_SESIONES_ESTADO CHECK (estado_sesion IN ('ACTIVA','CERRADA','REVOCADA','EXPIRADA')),
    CONSTRAINT CHK_SECURITY_SESIONES_FECHAS CHECK (fecha_expiracion_utc > fecha_inicio_utc)
);

CREATE TABLE security.API_CLIENTES (
    id_api_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    api_cliente_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_cliente_api VARCHAR(30) NOT NULL,
    nombre_cliente_api VARCHAR(100) NOT NULL,
    tipo_autenticacion VARCHAR(20) NOT NULL DEFAULT 'JWT',
    api_key_hash VARCHAR(500) NULL,
    client_secret_hash VARCHAR(500) NULL,
    permite_consulta_disponibilidad BOOLEAN NOT NULL DEFAULT TRUE,
    permite_sincronizacion_reservas BOOLEAN NOT NULL DEFAULT FALSE,
    estado_api_cliente CHAR(3) NOT NULL DEFAULT 'ACT',
    fecha_rotacion_credenciales_utc TIMESTAMPTZ(0) NULL,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SECURITY_API_CLIENTES PRIMARY KEY (id_api_cliente),
    CONSTRAINT UQ_SECURITY_API_CLIENTES_GUID UNIQUE (api_cliente_guid),
    CONSTRAINT UQ_SECURITY_API_CLIENTES_CODIGO UNIQUE (codigo_cliente_api),
    CONSTRAINT CHK_SECURITY_API_CLIENTES_TIPO CHECK (tipo_autenticacion IN ('JWT','OAUTH2','APIKEY')),
    CONSTRAINT CHK_SECURITY_API_CLIENTES_ESTADO CHECK (estado_api_cliente IN ('ACT','INA'))
);

-- =====================================================
-- AUDITORÍA
-- =====================================================
CREATE TABLE audit.AUD_EVENTOS (
    id_aud_evento BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aud_evento_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    esquema_afectado VARCHAR(50) NOT NULL,
    tabla_afectada VARCHAR(100) NOT NULL,
    operacion VARCHAR(20) NOT NULL,
    id_registro_afectado VARCHAR(100) NULL,
    datos_anteriores TEXT NULL,
    datos_nuevos TEXT NULL,
    usuario_app VARCHAR(100) NULL,
    login_bd VARCHAR(100) NULL,
    ip_origen VARCHAR(45) NULL,
    origen_evento VARCHAR(20) NOT NULL,
    fecha_evento_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_AUD_EVENTOS PRIMARY KEY (id_aud_evento),
    CONSTRAINT UQ_AUD_EVENTOS_GUID UNIQUE (aud_evento_guid),
    CONSTRAINT CHK_AUD_EVENTOS_OPERACION CHECK (operacion IN ('INSERT','UPDATE','DELETE','LOGIN','LOGOUT','FAILED_LOGIN','SYNC','CHECKOUT','CHECKIN')),
    CONSTRAINT CHK_AUD_EVENTOS_ORIGEN CHECK (origen_evento IN ('WEB','POS','BOOKING','APP','DB','API'))
);

CREATE TABLE audit.AUD_INTENTOS_LOGIN (
    id_aud_login BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aud_login_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    username_intentado VARCHAR(120) NOT NULL,
    correo_intentado VARCHAR(120) NULL,
    resultado VARCHAR(20) NOT NULL,
    motivo VARCHAR(200) NULL,
    ip_origen VARCHAR(45) NULL,
    user_agent VARCHAR(300) NULL,
    fecha_evento_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_AUD_INTENTOS_LOGIN PRIMARY KEY (id_aud_login),
    CONSTRAINT UQ_AUD_INTENTOS_LOGIN_GUID UNIQUE (aud_login_guid),
    CONSTRAINT CHK_AUD_INTENTOS_LOGIN_RESULTADO CHECK (resultado IN ('EXITOSO','FALLIDO','BLOQUEADO'))
);

-- =====================================================
-- ÍNDICES ÚTILES
-- =====================================================
CREATE INDEX IX_RESERVAS_VEHICULO_FECHAS ON rental.RESERVAS (id_vehiculo, fecha_hora_recogida, fecha_hora_devolucion, estado_reserva);

CREATE INDEX IX_RESERVAS_CLIENTE ON rental.RESERVAS (id_cliente, fecha_hora_recogida DESC);

CREATE INDEX IX_VEHICULOS_BUSQUEDA ON rental.VEHICULOS (localizacion_actual, id_categoria, id_marca, tipo_transmision, estado_operativo);

CREATE INDEX IX_PAGOS_RESERVA ON rental.PAGOS (id_reserva, estado_pago, fecha_pago_utc DESC);

CREATE INDEX IX_AUD_EVENTOS_TABLA_FECHA ON audit.AUD_EVENTOS (tabla_afectada, fecha_evento_utc DESC);

-- =====================================================
-- DATOS BASE DE SEGURIDAD (sin contraseña en texto plano)
-- =====================================================
INSERT INTO security.ROLES (nombre_rol, descripcion_rol, es_sistema, creado_por_usuario)
VALUES
('ADMIN','Administrador total del sistema',TRUE,'SYSTEM'),
('AGENTE_POS','Operador de oficina',TRUE,'SYSTEM'),
('CLIENTE_WEB','Cliente del e-commerce',TRUE,'SYSTEM'),
('API_BOOKING','Cliente técnico para Booking',TRUE,'SYSTEM');

INSERT INTO security.PERMISOS (codigo_permiso, modulo, accion, descripcion_permiso, creado_por_usuario)
VALUES
('vehiculos.read','vehiculos','READ','Consultar vehículos','SYSTEM'),
('vehiculos.write','vehiculos','UPDATE','Gestionar vehículos','SYSTEM'),
('reservas.read','reservas','READ','Consultar reservas','SYSTEM'),
('reservas.write','reservas','CREATE','Crear y modificar reservas','SYSTEM'),
('pagos.write','pagos','CREATE','Registrar pagos','SYSTEM'),
('contratos.write','contratos','UPDATE','Gestionar contratos','SYSTEM'),
('api.booking.read','api','READ','Consultar disponibilidad OTA','SYSTEM'),
('api.booking.write','api','CREATE','Sincronizar reservas OTA','SYSTEM');

INSERT INTO security.ROLES_PERMISOS (id_rol, id_permiso, creado_por_usuario)
SELECT r.id_rol, p.id_permiso, 'SYSTEM'
FROM security.ROLES r
JOIN security.PERMISOS p ON
    (r.nombre_rol = 'ADMIN') OR
    (r.nombre_rol = 'AGENTE_POS' AND p.codigo_permiso IN ('vehiculos.read','vehiculos.write','reservas.read','reservas.write','pagos.write','contratos.write')) OR
    (r.nombre_rol = 'CLIENTE_WEB' AND p.codigo_permiso IN ('vehiculos.read','reservas.read','reservas.write')) OR
    (r.nombre_rol = 'API_BOOKING' AND p.codigo_permiso IN ('api.booking.read','api.booking.write'));

/*
  Usuario demo de desarrollo:
  username sugerido: admin.dev
  contraseña de desarrollo para sembrar desde la app: 12345
  En esta DDL NO se inserta el texto plano. Se debe insertar el hash/salt generado por la app.
*/

-- Nota:
-- row_version se maneja como BIGINT con DEFAULT 1.
-- En PostgreSQL puedes incrementarlo desde la app o agregar triggers de versionado más adelante.
