-- =====================================================
-- MS.Localizaciones - redcar_localizaciones_db
-- PostgreSQL 15+ / 16+
-- =====================================================
-- Dominio: paises, ciudades, oficinas/sucursales (localizaciones)
-- y stock fisico de extras por localizacion.
--
-- Cross-service: id_extra (en localizacion_extra_stock) apunta
-- a catalogo.extras. SE ELIMINA la FK. Se conserva la columna
-- como referencia blanda y se anade extra_guid para identidad
-- canonica cross-service.
-- =====================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS localizaciones;

-- =====================================================
-- paises
-- =====================================================
CREATE TABLE localizaciones.paises (
    id_pais INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pais_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_iso2 CHAR(2) NOT NULL,
    nombre_pais VARCHAR(100) NOT NULL,
    estado_pais CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_paises PRIMARY KEY (id_pais),
    CONSTRAINT UQ_paises_GUID UNIQUE (pais_guid),
    CONSTRAINT UQ_paises_ISO2 UNIQUE (codigo_iso2),
    CONSTRAINT UQ_paises_NOMBRE UNIQUE (nombre_pais),
    CONSTRAINT CHK_paises_ESTADO CHECK (estado_pais IN ('ACT','INA')),
    CONSTRAINT CHK_paises_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

-- =====================================================
-- ciudades
-- =====================================================
CREATE TABLE localizaciones.ciudades (
    id_ciudad INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ciudad_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    id_pais INT NOT NULL,
    nombre_ciudad VARCHAR(100) NOT NULL,
    estado_ciudad CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_ciudades PRIMARY KEY (id_ciudad),
    CONSTRAINT UQ_ciudades_GUID UNIQUE (ciudad_guid),
    CONSTRAINT UQ_ciudades_PAIS_NOMBRE UNIQUE (id_pais, nombre_ciudad),
    CONSTRAINT FK_ciudades_paises FOREIGN KEY (id_pais)
        REFERENCES localizaciones.paises(id_pais),
    CONSTRAINT CHK_ciudades_ESTADO CHECK (estado_ciudad IN ('ACT','INA')),
    CONSTRAINT CHK_ciudades_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

-- =====================================================
-- localizaciones (oficinas/sucursales)
-- =====================================================
CREATE TABLE localizaciones.localizaciones (
    id_localizacion INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    localizacion_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_localizacion VARCHAR(20) NOT NULL,
    nombre_localizacion VARCHAR(100) NOT NULL,
    id_ciudad INT NOT NULL,
    direccion_localizacion VARCHAR(200) NOT NULL,
    telefono_contacto VARCHAR(20) NOT NULL,
    correo_contacto VARCHAR(120) NOT NULL,
    horario_atencion VARCHAR(120) NOT NULL,
    zona_horaria VARCHAR(50) NOT NULL DEFAULT 'America/Guayaquil',
    latitud DECIMAL(9,6) NULL,
    longitud DECIMAL(9,6) NULL,
    estado_localizacion CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_localizaciones PRIMARY KEY (id_localizacion),
    CONSTRAINT UQ_localizaciones_GUID UNIQUE (localizacion_guid),
    CONSTRAINT UQ_localizaciones_CODIGO UNIQUE (codigo_localizacion),
    CONSTRAINT FK_localizaciones_ciudades FOREIGN KEY (id_ciudad)
        REFERENCES localizaciones.ciudades(id_ciudad),
    CONSTRAINT CHK_localizaciones_ESTADO CHECK (estado_localizacion IN ('ACT','INA')),
    CONSTRAINT CHK_localizaciones_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

-- =====================================================
-- localizacion_extra_stock (cross-service: id_extra apunta a catalogo)
-- =====================================================
CREATE TABLE localizaciones.localizacion_extra_stock (
    id_localizacion_extra_stock INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stock_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    id_localizacion INT NOT NULL,
    -- referencia cross-service a catalogo.extras (sin FK)
    id_extra INT NOT NULL,
    extra_guid UUID NULL,
    stock_disponible INT NOT NULL,
    stock_reservado INT NOT NULL DEFAULT 0,
    estado_stock CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_localizacion_extra_stock PRIMARY KEY (id_localizacion_extra_stock),
    CONSTRAINT UQ_localizacion_extra_stock_GUID UNIQUE (stock_guid),
    CONSTRAINT UQ_localizacion_extra_stock UNIQUE (id_localizacion, id_extra),
    CONSTRAINT FK_localizacion_extra_stock_localizaciones FOREIGN KEY (id_localizacion)
        REFERENCES localizaciones.localizaciones(id_localizacion),
    CONSTRAINT CHK_localizacion_extra_stock_VALORES CHECK (
        stock_disponible >= 0 AND stock_reservado >= 0 AND stock_reservado <= stock_disponible
    ),
    CONSTRAINT CHK_localizacion_extra_stock_ESTADO CHECK (estado_stock IN ('ACT','INA')),
    CONSTRAINT CHK_localizacion_extra_stock_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

-- =====================================================
-- Indices utiles
-- =====================================================
CREATE INDEX IX_localizaciones_CIUDAD ON localizaciones.localizaciones (id_ciudad, estado_localizacion);
CREATE INDEX IX_LOC_EXTRA_STOCK_EXTRA ON localizaciones.localizacion_extra_stock (id_extra);
CREATE INDEX IX_LOC_EXTRA_STOCK_EXTRA_GUID ON localizaciones.localizacion_extra_stock (extra_guid);
