-- =====================================================
-- MS.Catalogo - redcar_catalogo_db
-- PostgreSQL 15+ / 16+
-- =====================================================
-- Dominio: marcas, categorias, vehiculos, extras y mantenimientos.
--
-- Cross-service: vehiculos.localizacion_actual apunta a localizaciones.localizaciones.
-- SE ELIMINA la FK. Se conservan ambas referencias (id + guid).
-- =====================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS catalogo;

-- =====================================================
-- marca_vehiculos
-- =====================================================
CREATE TABLE catalogo.marca_vehiculos (
    id_marca INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    marca_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_marca VARCHAR(20) NOT NULL,
    nombre_marca VARCHAR(100) NOT NULL,
    descripcion_marca VARCHAR(250) NULL,
    estado_marca CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_marca_vehiculos PRIMARY KEY (id_marca),
    CONSTRAINT UQ_marca_vehiculos_GUID UNIQUE (marca_guid),
    CONSTRAINT UQ_marca_vehiculos_CODIGO UNIQUE (codigo_marca),
    CONSTRAINT UQ_marca_vehiculos_NOMBRE UNIQUE (nombre_marca),
    CONSTRAINT CHK_marca_vehiculos_ESTADO CHECK (estado_marca IN ('ACT','INA')),
    CONSTRAINT CHK_marca_vehiculos_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

-- =====================================================
-- categoria_vehiculos
-- =====================================================
CREATE TABLE catalogo.categoria_vehiculos (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    categoria_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_categoria VARCHAR(20) NOT NULL,
    nombre_categoria VARCHAR(100) NOT NULL,
    descripcion_categoria VARCHAR(250) NULL,
    kilometraje_ilimitado BOOLEAN NOT NULL DEFAULT TRUE,
    limite_km_dia INT NULL,
    cargo_km_excedente DECIMAL(10,2) NULL,
    estado_categoria CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_categoria_vehiculos PRIMARY KEY (id_categoria),
    CONSTRAINT UQ_categoria_vehiculos_GUID UNIQUE (categoria_guid),
    CONSTRAINT UQ_categoria_vehiculos_CODIGO UNIQUE (codigo_categoria),
    CONSTRAINT UQ_categoria_vehiculos_NOMBRE UNIQUE (nombre_categoria),
    CONSTRAINT CHK_CATEGORIA_ESTADO CHECK (estado_categoria IN ('ACT','INA')),
    CONSTRAINT CHK_CATEGORIA_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE)),
    CONSTRAINT CHK_CATEGORIA_KM CHECK (
        (kilometraje_ilimitado = TRUE AND limite_km_dia IS NULL AND cargo_km_excedente IS NULL)
        OR
        (kilometraje_ilimitado = FALSE AND limite_km_dia > 0 AND cargo_km_excedente >= 0)
    )
);

-- =====================================================
-- extras
-- =====================================================
CREATE TABLE catalogo.extras (
    id_extra INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    extra_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_extra VARCHAR(20) NOT NULL,
    nombre_extra VARCHAR(100) NOT NULL,
    descripcion_extra VARCHAR(250) NOT NULL,
    tipo_extra VARCHAR(20) NOT NULL DEFAULT 'SERVICIO',
    requiere_stock BOOLEAN NOT NULL DEFAULT FALSE,
    valor_fijo DECIMAL(10,2) NOT NULL,
    estado_extra CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    origen_registro VARCHAR(20) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_extras PRIMARY KEY (id_extra),
    CONSTRAINT UQ_extras_GUID UNIQUE (extra_guid),
    CONSTRAINT UQ_extras_CODIGO UNIQUE (codigo_extra),
    CONSTRAINT CHK_extras_ESTADO CHECK (estado_extra IN ('ACT','INA')),
    CONSTRAINT CHK_extras_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE)),
    CONSTRAINT CHK_extras_VALOR_FIJO CHECK (valor_fijo >= 0),
    CONSTRAINT CHK_extras_TIPO CHECK (tipo_extra IN ('SERVICIO','FISICO','SEGURO'))
);

-- =====================================================
-- vehiculos (cross-service: localizacion_actual -> localizaciones)
-- =====================================================
CREATE TABLE catalogo.vehiculos (
    id_vehiculo INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vehiculo_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_interno_vehiculo VARCHAR(20) NOT NULL,
    placa_vehiculo VARCHAR(15) NOT NULL,
    id_marca INT NOT NULL,
    id_categoria INT NOT NULL,
    modelo_vehiculo VARCHAR(50) NOT NULL,
    anio_fabricacion SMALLINT NOT NULL,
    color_vehiculo VARCHAR(30) NOT NULL,
    tipo_combustible VARCHAR(20) NOT NULL,
    tipo_transmision VARCHAR(20) NOT NULL,
    capacidad_pasajeros SMALLINT NOT NULL,
    capacidad_maletas SMALLINT NOT NULL,
    numero_puertas SMALLINT NOT NULL,
    -- referencia cross-service a localizaciones.localizaciones (sin FK)
    localizacion_actual INT NOT NULL,
    localizacion_guid UUID NULL,
    precio_base_dia DECIMAL(10,2) NOT NULL,
    kilometraje_actual INT NOT NULL,
    aire_acondicionado BOOLEAN NOT NULL DEFAULT TRUE,
    estado_operativo VARCHAR(20) NOT NULL DEFAULT 'DISPONIBLE',
    observaciones_generales VARCHAR(300) NULL,
    imagen_referencial_url VARCHAR(300) NULL,
    estado_vehiculo CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    origen_registro VARCHAR(20) NOT NULL,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    modificado_desde_ip VARCHAR(45) NULL,
    fecha_inhabilitacion_utc TIMESTAMPTZ(0) NULL,
    motivo_inhabilitacion VARCHAR(200) NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_vehiculos PRIMARY KEY (id_vehiculo),
    CONSTRAINT UQ_vehiculos_GUID UNIQUE (vehiculo_guid),
    CONSTRAINT UQ_vehiculos_CODIGO UNIQUE (codigo_interno_vehiculo),
    CONSTRAINT UQ_vehiculos_PLACA UNIQUE (placa_vehiculo),
    CONSTRAINT FK_vehiculos_MARCA FOREIGN KEY (id_marca)
        REFERENCES catalogo.marca_vehiculos(id_marca),
    CONSTRAINT FK_vehiculos_CATEGORIA FOREIGN KEY (id_categoria)
        REFERENCES catalogo.categoria_vehiculos(id_categoria),
    CONSTRAINT CHK_vehiculos_ESTADO CHECK (estado_vehiculo IN ('ACT','INA')),
    CONSTRAINT CHK_vehiculos_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE)),
    CONSTRAINT CHK_vehiculos_PRECIO_BASE CHECK (precio_base_dia > 0),
    CONSTRAINT CHK_vehiculos_KILOMETRAJE CHECK (kilometraje_actual >= 0),
    CONSTRAINT CHK_vehiculos_CAP_PASAJEROS CHECK (capacidad_pasajeros > 0),
    CONSTRAINT CHK_vehiculos_CAP_MALETAS CHECK (capacidad_maletas >= 0),
    CONSTRAINT CHK_vehiculos_NUM_PUERTAS CHECK (numero_puertas > 0),
    CONSTRAINT CHK_vehiculos_ANIO CHECK (anio_fabricacion BETWEEN 1990 AND (EXTRACT(YEAR FROM CURRENT_DATE)::INT + 1)),
    CONSTRAINT CHK_vehiculos_COMBUSTIBLE CHECK (tipo_combustible IN ('GASOLINA','DIESEL','HIBRIDO','ELECTRICO')),
    CONSTRAINT CHK_vehiculos_TRANSMISION CHECK (tipo_transmision IN ('AUTOMATICA','MANUAL')),
    CONSTRAINT CHK_vehiculos_ESTADO_OPERATIVO CHECK (estado_operativo IN ('DISPONIBLE','RESERVADO','ALQUILADO','MANTENIMIENTO','TALLER','FUERA_SERVICIO'))
);

-- =====================================================
-- mantenimientos (mismo dominio, FK a vehiculos se conserva)
-- =====================================================
CREATE TABLE catalogo.mantenimientos (
    id_mantenimiento INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mantenimiento_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_mantenimiento VARCHAR(30) NOT NULL,
    id_vehiculo INT NOT NULL,
    tipo_mantenimiento VARCHAR(20) NOT NULL,
    fecha_inicio_utc TIMESTAMPTZ(0) NOT NULL,
    fecha_fin_utc TIMESTAMPTZ(0) NULL,
    kilometraje_mantenimiento INT NOT NULL,
    costo_mantenimiento DECIMAL(12,2) NOT NULL DEFAULT 0,
    proveedor_taller VARCHAR(120) NULL,
    estado_mantenimiento VARCHAR(20) NOT NULL DEFAULT 'ABIERTO',
    observaciones VARCHAR(300) NULL,
    creado_por_usuario VARCHAR(100) NOT NULL,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_mantenimientos PRIMARY KEY (id_mantenimiento),
    CONSTRAINT UQ_mantenimientos_GUID UNIQUE (mantenimiento_guid),
    CONSTRAINT UQ_mantenimientos_CODIGO UNIQUE (codigo_mantenimiento),
    CONSTRAINT FK_mantenimientos_vehiculos FOREIGN KEY (id_vehiculo)
        REFERENCES catalogo.vehiculos(id_vehiculo),
    CONSTRAINT CHK_mantenimientos_TIPO CHECK (tipo_mantenimiento IN ('PREVENTIVO','CORRECTIVO','TALLER')),
    CONSTRAINT CHK_mantenimientos_ESTADO CHECK (estado_mantenimiento IN ('ABIERTO','CERRADO','ANULADO')),
    CONSTRAINT CHK_mantenimientos_KM CHECK (kilometraje_mantenimiento >= 0),
    CONSTRAINT CHK_mantenimientos_COSTO CHECK (costo_mantenimiento >= 0),
    CONSTRAINT CHK_mantenimientos_FECHAS CHECK (fecha_fin_utc IS NULL OR fecha_fin_utc >= fecha_inicio_utc)
);

-- =====================================================
-- Indices utiles
-- =====================================================
CREATE INDEX IX_vehiculos_BUSQUEDA ON catalogo.vehiculos (localizacion_actual, id_categoria, id_marca, tipo_transmision, estado_operativo);
CREATE INDEX IX_vehiculos_LOC_GUID ON catalogo.vehiculos (localizacion_guid);
CREATE INDEX IX_mantenimientos_VEHICULO ON catalogo.mantenimientos (id_vehiculo, estado_mantenimiento);
