-- =====================================================
-- MS.Seguridad - redcar_seguridad_db
-- PostgreSQL 15+ / 16+
-- =====================================================
-- Dominio: usuarios de aplicacion, roles, permisos, sesiones,
-- clientes API y auditoria de eventos y de intentos de login.
--
-- Cross-service: usuarios_app.id_cliente apuntaba a rental.clientes.
-- SE ELIMINA la FK. Se conserva la referencia (id + guid).
-- =====================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS security;
CREATE SCHEMA IF NOT EXISTS audit;

-- =====================================================
-- roles
-- =====================================================
CREATE TABLE security.roles (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rol_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    nombre_rol VARCHAR(50) NOT NULL,
    descripcion_rol VARCHAR(200) NULL,
    es_sistema BOOLEAN NOT NULL DEFAULT FALSE,
    estado_rol CHAR(3) NOT NULL DEFAULT 'ACT',
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SECURITY_roles PRIMARY KEY (id_rol),
    CONSTRAINT UQ_SECURITY_roles_GUID UNIQUE (rol_guid),
    CONSTRAINT UQ_SECURITY_roles_NOMBRE UNIQUE (nombre_rol),
    CONSTRAINT CHK_SECURITY_roles_ESTADO CHECK (estado_rol IN ('ACT','INA'))
);

-- =====================================================
-- permisos
-- =====================================================
CREATE TABLE security.permisos (
    id_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    permiso_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_permiso VARCHAR(80) NOT NULL,
    modulo VARCHAR(50) NOT NULL,
    accion VARCHAR(30) NOT NULL,
    descripcion_permiso VARCHAR(200) NULL,
    estado_permiso CHAR(3) NOT NULL DEFAULT 'ACT',
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SECURITY_permisos PRIMARY KEY (id_permiso),
    CONSTRAINT UQ_SECURITY_permisos_GUID UNIQUE (permiso_guid),
    CONSTRAINT UQ_SECURITY_permisos_CODIGO UNIQUE (codigo_permiso),
    CONSTRAINT CHK_SECURITY_permisos_ESTADO CHECK (estado_permiso IN ('ACT','INA')),
    CONSTRAINT CHK_SECURITY_permisos_ACCION CHECK (accion IN ('CREATE','READ','UPDATE','DELETE','APPROVE','EXPORT','LOGIN'))
);

-- =====================================================
-- usuarios_app (cross-service: id_cliente -> clientes)
-- =====================================================
CREATE TABLE security.usuarios_app (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    username VARCHAR(50) NOT NULL,
    correo VARCHAR(120) NOT NULL,
    password_hash VARCHAR(500) NOT NULL,
    password_salt VARCHAR(250) NOT NULL,
    password_hint VARCHAR(100) NULL,
    requiere_cambio_password BOOLEAN NOT NULL DEFAULT TRUE,
    estado_usuario CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    intentos_fallidos SMALLINT NOT NULL DEFAULT 0,
    bloqueado_hasta_utc TIMESTAMPTZ(0) NULL,
    ultimo_login_utc TIMESTAMPTZ(0) NULL,
    -- referencia cross-service a clientes.clientes (sin FK)
    id_cliente INT NULL,
    cliente_guid UUID NULL,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SECURITY_usuarios_app PRIMARY KEY (id_usuario),
    CONSTRAINT UQ_SECURITY_usuarios_app_GUID UNIQUE (usuario_guid),
    CONSTRAINT UQ_SECURITY_usuarios_app_USERNAME UNIQUE (username),
    CONSTRAINT UQ_SECURITY_usuarios_app_CORREO UNIQUE (correo),
    CONSTRAINT CHK_SECURITY_usuarios_app_ESTADO CHECK (estado_usuario IN ('ACT','INA','BLQ')),
    CONSTRAINT CHK_SECURITY_usuarios_app_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE)),
    CONSTRAINT CHK_SECURITY_usuarios_app_ACTIVO CHECK (activo IN (FALSE, TRUE)),
    CONSTRAINT CHK_SECURITY_usuarios_app_INTENTOS CHECK (intentos_fallidos >= 0)
);

-- =====================================================
-- usuarios_roles
-- =====================================================
CREATE TABLE security.usuarios_roles (
    id_usuario_rol INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario INT NOT NULL,
    id_rol INT NOT NULL,
    estado_usuario_rol CHAR(3) NOT NULL DEFAULT 'ACT',
    es_eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    modificado_por_usuario VARCHAR(100) NULL,
    fecha_modificacion_utc TIMESTAMPTZ(0) NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SECURITY_usuarios_roles PRIMARY KEY (id_usuario_rol),
    CONSTRAINT UQ_SECURITY_usuarios_roles UNIQUE (id_usuario, id_rol),
    CONSTRAINT FK_SECURITY_usuarios_roles_USUARIOS FOREIGN KEY (id_usuario)
        REFERENCES security.usuarios_app(id_usuario),
    CONSTRAINT FK_SECURITY_usuarios_roles_roles FOREIGN KEY (id_rol)
        REFERENCES security.roles(id_rol),
    CONSTRAINT CHK_SECURITY_usuarios_roles_ESTADO CHECK (estado_usuario_rol IN ('ACT','INA')),
    CONSTRAINT CHK_SECURITY_usuarios_roles_ELIMINADO CHECK (es_eliminado IN (FALSE, TRUE))
);

-- =====================================================
-- roles_permisos
-- =====================================================
CREATE TABLE security.roles_permisos (
    id_rol_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_rol INT NOT NULL,
    id_permiso INT NOT NULL,
    estado_rol_permiso CHAR(3) NOT NULL DEFAULT 'ACT',
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SECURITY_roles_permisos PRIMARY KEY (id_rol_permiso),
    CONSTRAINT UQ_SECURITY_roles_permisos UNIQUE (id_rol, id_permiso),
    CONSTRAINT FK_SECURITY_roles_permisos_roles FOREIGN KEY (id_rol)
        REFERENCES security.roles(id_rol),
    CONSTRAINT FK_SECURITY_roles_permisos_permisos FOREIGN KEY (id_permiso)
        REFERENCES security.permisos(id_permiso),
    CONSTRAINT CHK_SECURITY_roles_permisos_ESTADO CHECK (estado_rol_permiso IN ('ACT','INA'))
);

-- =====================================================
-- sesiones
-- =====================================================
CREATE TABLE security.sesiones (
    id_sesion BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sesion_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    id_usuario INT NOT NULL,
    token_id VARCHAR(120) NOT NULL,
    refresh_token_hash VARCHAR(500) NULL,
    ip_origen VARCHAR(45) NULL,
    user_agent VARCHAR(300) NULL,
    fecha_inicio_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    fecha_expiracion_utc TIMESTAMPTZ(0) NOT NULL,
    fecha_cierre_utc TIMESTAMPTZ(0) NULL,
    estado_sesion VARCHAR(20) NOT NULL DEFAULT 'ACTIVA',
    creado_por_usuario VARCHAR(100) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SECURITY_sesiones PRIMARY KEY (id_sesion),
    CONSTRAINT UQ_SECURITY_sesiones_GUID UNIQUE (sesion_guid),
    CONSTRAINT UQ_SECURITY_sesiones_TOKEN UNIQUE (token_id),
    CONSTRAINT FK_SECURITY_sesiones_USUARIOS FOREIGN KEY (id_usuario)
        REFERENCES security.usuarios_app(id_usuario),
    CONSTRAINT CHK_SECURITY_sesiones_ESTADO CHECK (estado_sesion IN ('ACTIVA','CERRADA','REVOCADA','EXPIRADA')),
    CONSTRAINT CHK_SECURITY_sesiones_FECHAS CHECK (fecha_expiracion_utc > fecha_inicio_utc)
);

-- =====================================================
-- api_clientes (clientes tecnicos OTA / integraciones)
-- =====================================================
CREATE TABLE security.api_clientes (
    id_api_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    api_cliente_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    codigo_cliente_api VARCHAR(30) NOT NULL,
    nombre_cliente_api VARCHAR(100) NOT NULL,
    tipo_autenticacion VARCHAR(20) NOT NULL DEFAULT 'JWT',
    api_key_hash VARCHAR(500) NULL,
    client_secret_hash VARCHAR(500) NULL,
    permite_consulta_disponibilidad BOOLEAN NOT NULL DEFAULT TRUE,
    permite_sincronizacion_reservas BOOLEAN NOT NULL DEFAULT FALSE,
    estado_api_cliente CHAR(3) NOT NULL DEFAULT 'ACT',
    fecha_rotacion_credenciales_utc TIMESTAMPTZ(0) NULL,
    fecha_registro_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    creado_por_usuario VARCHAR(100) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SECURITY_api_clientes PRIMARY KEY (id_api_cliente),
    CONSTRAINT UQ_SECURITY_api_clientes_GUID UNIQUE (api_cliente_guid),
    CONSTRAINT UQ_SECURITY_api_clientes_CODIGO UNIQUE (codigo_cliente_api),
    CONSTRAINT CHK_SECURITY_api_clientes_TIPO CHECK (tipo_autenticacion IN ('JWT','OAUTH2','APIKEY')),
    CONSTRAINT CHK_SECURITY_api_clientes_ESTADO CHECK (estado_api_cliente IN ('ACT','INA'))
);

-- =====================================================
-- AUDITORIA - eventos generales
-- =====================================================
CREATE TABLE audit.aud_eventos (
    id_aud_evento BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aud_evento_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    esquema_afectado VARCHAR(50) NOT NULL,
    tabla_afectada VARCHAR(100) NOT NULL,
    operacion VARCHAR(20) NOT NULL,
    id_registro_afectado VARCHAR(100) NULL,
    datos_anteriores TEXT NULL,
    datos_nuevos TEXT NULL,
    usuario_app VARCHAR(100) NULL,
    login_bd VARCHAR(100) NULL,
    ip_origen VARCHAR(45) NULL,
    origen_evento VARCHAR(20) NOT NULL,
    fecha_evento_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_aud_eventos PRIMARY KEY (id_aud_evento),
    CONSTRAINT UQ_aud_eventos_GUID UNIQUE (aud_evento_guid),
    CONSTRAINT CHK_aud_eventos_OPERACION CHECK (operacion IN ('INSERT','UPDATE','DELETE','LOGIN','LOGOUT','FAILED_LOGIN','SYNC','CHECKOUT','CHECKIN')),
    CONSTRAINT CHK_aud_eventos_ORIGEN CHECK (origen_evento IN ('WEB','POS','BOOKING','APP','DB','API'))
);

-- =====================================================
-- AUDITORIA - intentos de login
-- =====================================================
CREATE TABLE audit.aud_intentos_login (
    id_aud_login BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aud_login_guid UUID NOT NULL DEFAULT gen_random_uuid(),
    username_intentado VARCHAR(120) NOT NULL,
    correo_intentado VARCHAR(120) NULL,
    resultado VARCHAR(20) NOT NULL,
    motivo VARCHAR(200) NULL,
    ip_origen VARCHAR(45) NULL,
    user_agent VARCHAR(300) NULL,
    fecha_evento_utc TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    row_version BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_aud_intentos_login PRIMARY KEY (id_aud_login),
    CONSTRAINT UQ_aud_intentos_login_GUID UNIQUE (aud_login_guid),
    CONSTRAINT CHK_aud_intentos_login_RESULTADO CHECK (resultado IN ('EXITOSO','FALLIDO','BLOQUEADO'))
);

-- =====================================================
-- Indices utiles
-- =====================================================
CREATE INDEX IX_usuarios_app_CLIENTE_GUID ON security.usuarios_app (cliente_guid);
CREATE INDEX IX_usuarios_app_ESTADO ON security.usuarios_app (estado_usuario, es_eliminado);
CREATE INDEX IX_sesiones_USUARIO ON security.sesiones (id_usuario, estado_sesion);
CREATE INDEX IX_aud_eventos_TABLA_FECHA ON audit.aud_eventos (tabla_afectada, fecha_evento_utc DESC);
CREATE INDEX IX_AUD_LOGIN_USERNAME_FECHA ON audit.aud_intentos_login (username_intentado, fecha_evento_utc DESC);
